export const SELECT_LOCATION = 'SELECT_LOCATION'
export const ADD_FOOD_ITEM = 'ADD_FOOD_ITEM'
export const REMOVE_FOOD_ITEM = 'REMOVE_FOOD_ITEM'
export const ADD_DRINK_ITEM = 'ADD_DRINK_ITEM'
export const REMOVE_DRINK_ITEM = 'REMOVE_DRINK_ITEM'

export const SELECT_PICKUP_TIME = 'SELECT_PICKUP_TIME'
export const SELECT_PICKUP_DATE = 'SELECT_PICKUP_DATE'
export const SELECT_PICKUP_LOCATION = 'SELECT_PICKUP_LOCATION'
